version: "3.8"
services:
  db:
    image: postgres:latest
    env_file: 
      ./env/.env
    ports:
      - "5432:5432"
    volumes:
      - ./Database/postgresqldata:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/1_init.sql
    networks:
      - webnet
  backend:
    build: ./Backend/
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - webnet
  frontend:
    build: ./front-end/
    ports:
      - "3000:3000"
    depends_on:
      - db
      - backend
    networks:
      - webnet
volumes:
  postgresqldata:
networks:
  webnet: